import enum


class Phase(enum.Enum):
    PLAN_PATH_TO_CLOSED_DOOR=1,
    FOLLOW_PATH_TO_CLOSED_DOOR=2,
    OPEN_DOOR=3,
    PLAN_PATH_TO_OPEN_DOOR=4,
    FOLLOW_PATH_TO_OPEN_DOOR=5,
    PLAN_ROOM_SEARCH=6,
    SEARCH_ROOM=7,
    PLAN_PATH_TO_BLOCK=8,
    FOLLOW_PATH_TO_BLOCK=9,
    GRAB_BLOCK=10,
    PLAN_PATH_TO_DROP=11,
    RETURN_GOAL_BLOCK=12,
    DROP_BLOCK=13